apiVersion: v1
kind: Service
metadata:
  name: moviesense-backend
  labels:
    app: moviesense-backend
    team: moviesense-backend
spec:
  type: NodePort
  selector:
    service: moviesense-backend
  ports:
    - name: metrics
      port: 8000 # service port (frontend will call this)
      targetPort: 8081 # container port
      nodePort: 30001
