apiVersion: v1
kind: Service
metadata:
  name: moviesense-frontend
  labels:
    service: moviesense-frontend
spec:
  type: NodePort
  selector:
    service: moviesense-frontend
  ports:
    - name: http
      port: {{ .Values.moviesensefrontend.port }} # ClusterIP port (internal service port)
      targetPort: {{ .Values.moviesensefrontend.targetPort }} # The container port your React app listens on
      nodePort: {{ .Values.moviesensefrontend.nodePort }} # NodePort (accessible externally on worker nodes)
