apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgreaccount-deployment
  labels:
    service: postgreaccount
spec:
  serviceName: postgreaccount-service   # must be under spec
  replicas: 1
  selector:
    matchLabels:
      service: postgreaccount
  template:
    metadata:
      labels:
        service: postgreaccount
    spec:
      containers:
        - name: postgreaccount
          image: postgres:16
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]   # added for Istio
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: 1234
            - name: POSTGRES_DB
              value: mydb
          resources:
            limits:
              cpu: 200m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 700Mi
      {{- with .Values.moviesensebackend.affinity }}
      affinity:
{{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.moviesensebackend.nodeSelector }}
      nodeSelector:
{{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.moviesensebackend.tolerations }}
      tolerations:
{{ toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: default
        volumeMode: Filesystem
        resources:
          requests:
            storage: 1Gi
