apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sysctl-vm-max-map-count
  namespace: kube-system
  labels:
    app: sysctl-vm-max-map-count
spec:
  selector:
    matchLabels:
      app: sysctl-vm-max-map-count
      release: final
  template:
    metadata:
      labels:
        app: sysctl-vm-max-map-count
        release: final
    spec:
      hostPID: true
      containers:
        - name: sysctl
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              sysctl -w vm.max_map_count=262144
              sleep infinity
          securityContext:
            privileged: true
      restartPolicy: Always
      tolerations:
        - operator: "Exists"
