name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          # For Docker Hub use docker.io or leave blank.
          registry: docker.io      
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: Movie-Recommender/movide_recommender
          # Build and publish to registry
          push: true
          # Build multi-arch images (optional: remove if not needed)
          platforms: linux/amd64
          # Tags to publish: update repo/name as required
          tags: |
            docker.io/vinyl48/moviesensebackend:latest
          # Useful metadata labels
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
